// <auto-generated />
using System;
using ManaWorksApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManaWorksApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CandidateStatusId")
                        .HasColumnType("int");

                    b.Property<int>("Childrens")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaritalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SocialProfile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CandidateId");

                    b.HasIndex("CandidateStatusId");

                    b.HasIndex("MaritalId");

                    b.ToTable("candidates");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateAddress", b =>
                {
                    b.Property<int>("CandidateAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidateAddressId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CandidateAddressId");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.ToTable("candidateaddresses");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateContact", b =>
                {
                    b.Property<int>("CandidateContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidateContactId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CandidateContactId");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.ToTable("candidatecontacts");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateCourse", b =>
                {
                    b.Property<int>("CandidateCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidateCourseId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Conclusion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CandidateCourseId");

                    b.HasIndex("CandidateId");

                    b.ToTable("candidatecourses");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateDocument", b =>
                {
                    b.Property<int>("CandidateDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidateDocumentId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CandidateDocumentId");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.ToTable("candidatedocuments");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateEducation", b =>
                {
                    b.Property<int>("CandidateEducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidateEducationId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Conclusion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EducationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CandidateEducationId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("EducationTypeId");

                    b.ToTable("candidateeducations");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateExperience", b =>
                {
                    b.Property<int>("CandidateExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidateExperienceId"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("Enterprise")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExperienceTimeId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReasonLeaving")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CandidateExperienceId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ExperienceTimeId");

                    b.ToTable("candidateexperiences");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateFunction", b =>
                {
                    b.Property<int>("CandidateFunctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidateFunctionId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceTimeId")
                        .HasColumnType("int");

                    b.Property<int>("FunctionId")
                        .HasColumnType("int");

                    b.Property<int>("FunctionWorkId")
                        .HasColumnType("int");

                    b.HasKey("CandidateFunctionId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ExperienceTimeId");

                    b.HasIndex("FunctionWorkId");

                    b.ToTable("CandidateFunction");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateObjective", b =>
                {
                    b.Property<int>("CandidateObjectiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidateObjectiveId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Pretension")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("WorkSupermarket")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CandidateObjectiveId");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.ToTable("candidateobjectives");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateSelection", b =>
                {
                    b.Property<int>("CandidateSelectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidateSelectionId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<bool?>("CurrentlyWorking")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("DisponibilityImediate")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("DisponibilityTime")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("DisponibilityWeekend")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DistanceHome")
                        .HasColumnType("longtext");

                    b.Property<int?>("ExperienceTimeId")
                        .HasColumnType("int");

                    b.Property<bool?>("FunctionExperience")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FunctionWorked")
                        .HasColumnType("longtext");

                    b.Property<string>("KnowingVacancy")
                        .HasColumnType("longtext");

                    b.Property<bool?>("MarketWorked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MarketWorkedDescription")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Pretension")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("RelevanceFormation")
                        .HasColumnType("longtext");

                    b.Property<int?>("WorkTimeId")
                        .HasColumnType("int");

                    b.HasKey("CandidateSelectionId");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.HasIndex("WorkTimeId");

                    b.ToTable("candidateselections");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateStatus", b =>
                {
                    b.Property<int>("CandidateStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidateStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CandidateStatusId");

                    b.ToTable("candidatestatus");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.EducationType", b =>
                {
                    b.Property<int>("EducationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EducationTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EducationTypeId");

                    b.ToTable("educationtypes");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.ExperienceTime", b =>
                {
                    b.Property<int>("ExperienceTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ExperienceTimeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ExperienceTimeId");

                    b.ToTable("experiencetimes");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.FunctionWork", b =>
                {
                    b.Property<int>("FunctionWorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FunctionWorkId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FunctionWorkId");

                    b.ToTable("functionworks");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.Marital", b =>
                {
                    b.Property<int>("MaritalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaritalId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaritalId");

                    b.ToTable("maritals");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.WorkTime", b =>
                {
                    b.Property<int>("WorkTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkTimeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("WorkTimeId");

                    b.ToTable("worktimes");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.ContractType", b =>
                {
                    b.Property<int>("ContractTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ContractTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ContractTypeId");

                    b.ToTable("contracttypes");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.JourneyType", b =>
                {
                    b.Property<int>("JourneyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("JourneyTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("JourneyTypeId");

                    b.ToTable("journeytypes");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.User.Profile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProfileId");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.User.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("ProfileId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Vacancy", b =>
                {
                    b.Property<int>("VacancyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VacancyId"));

                    b.Property<int>("ContractTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("JourneyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkTypeId")
                        .HasColumnType("int");

                    b.HasKey("VacancyId");

                    b.HasIndex("ContractTypeId");

                    b.HasIndex("JourneyTypeId");

                    b.HasIndex("WorkTypeId");

                    b.ToTable("vacancies");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.WorkType", b =>
                {
                    b.Property<int>("WorkTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("WorkTypeId");

                    b.ToTable("worktypes");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.Candidate", b =>
                {
                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.CandidateStatus", "CandidateStatus")
                        .WithMany()
                        .HasForeignKey("CandidateStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.Marital", "Marital")
                        .WithMany()
                        .HasForeignKey("MaritalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateStatus");

                    b.Navigation("Marital");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateAddress", b =>
                {
                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.Candidate", "Candidate")
                        .WithOne("CandidateAddress")
                        .HasForeignKey("ManaWorksApi.Domain.Entities.Candidate.CandidateAddress", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateContact", b =>
                {
                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.Candidate", "Candidate")
                        .WithOne("CandidateContact")
                        .HasForeignKey("ManaWorksApi.Domain.Entities.Candidate.CandidateContact", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateCourse", b =>
                {
                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.Candidate", null)
                        .WithMany("CandidateCourseList")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateDocument", b =>
                {
                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.Candidate", "Candidate")
                        .WithOne("CandidateDocument")
                        .HasForeignKey("ManaWorksApi.Domain.Entities.Candidate.CandidateDocument", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateEducation", b =>
                {
                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.Candidate", null)
                        .WithMany("CandidateEducationList")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.EducationType", "EducationType")
                        .WithMany()
                        .HasForeignKey("EducationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationType");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateExperience", b =>
                {
                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.Candidate", null)
                        .WithMany("CandidateExperienceList")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.ExperienceTime", "ExperienceTime")
                        .WithMany()
                        .HasForeignKey("ExperienceTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperienceTime");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateFunction", b =>
                {
                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.Candidate", null)
                        .WithMany("CandidateFunctionList")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.ExperienceTime", "ExperienceTime")
                        .WithMany()
                        .HasForeignKey("ExperienceTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.FunctionWork", "FunctionWork")
                        .WithMany()
                        .HasForeignKey("FunctionWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperienceTime");

                    b.Navigation("FunctionWork");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateObjective", b =>
                {
                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.Candidate", null)
                        .WithOne("CandidateObjective")
                        .HasForeignKey("ManaWorksApi.Domain.Entities.Candidate.CandidateObjective", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.CandidateSelection", b =>
                {
                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.Candidate", null)
                        .WithOne("CandidateSelection")
                        .HasForeignKey("ManaWorksApi.Domain.Entities.Candidate.CandidateSelection", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManaWorksApi.Domain.Entities.Candidate.WorkTime", "WorkTime")
                        .WithMany()
                        .HasForeignKey("WorkTimeId");

                    b.Navigation("WorkTime");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.User.User", b =>
                {
                    b.HasOne("ManaWorksApi.Domain.Entities.User.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Vacancy", b =>
                {
                    b.HasOne("ManaWorksApi.Domain.Entities.ContractType", "ContractType")
                        .WithMany()
                        .HasForeignKey("ContractTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManaWorksApi.Domain.Entities.JourneyType", "JourneyType")
                        .WithMany()
                        .HasForeignKey("JourneyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManaWorksApi.Domain.Entities.WorkType", "WorkType")
                        .WithMany()
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractType");

                    b.Navigation("JourneyType");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("ManaWorksApi.Domain.Entities.Candidate.Candidate", b =>
                {
                    b.Navigation("CandidateAddress")
                        .IsRequired();

                    b.Navigation("CandidateContact")
                        .IsRequired();

                    b.Navigation("CandidateCourseList");

                    b.Navigation("CandidateDocument")
                        .IsRequired();

                    b.Navigation("CandidateEducationList");

                    b.Navigation("CandidateExperienceList");

                    b.Navigation("CandidateFunctionList");

                    b.Navigation("CandidateObjective")
                        .IsRequired();

                    b.Navigation("CandidateSelection")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
